django_projects/locallibrary/catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

django_projects/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    prefix_default_language=False,
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_projects/locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=_('Enter a book genre (e.g. Science Fiction)'))

    def __str__(self):
        return self.name      
  
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text=_('Enter a brief description of the book'))
    isbn = models.CharField('ISBN', max_length=13, help_text=_('13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'))

    genre = models.ManyToManyField(Genre, help_text=_('Select a genre for this book'))

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text=_('Unique ID for this particular book across whole library'))
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    class LOAN_STATUS(models.TextChoices):
        MAINTENANCE = 'm', 'Maintenance'
        ON_LOAN = 'o', 'On loan'
        AVAILABLE = 'a', 'Available'
        RESERVED = 'r', 'Reserved'

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS.choices,
        blank=True,
        default="m",
        help_text=_("Book availability"),
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'
  
    def clean(self):
        super().clean()
        if self.date_of_death and self.date_of_birth:
            if self.date_of_death < self.date_of_birth:
                raise ValidationError(_('Death date cannot be before birth date.'))

django_projects/locallibrary/catalog/forms.py
from django import forms
from catalog.models import BookInstance
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text=_("Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data
    
class RenewBookModelForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

django_projects/locallibrary/catalog/views.py
from typing import Any
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.shortcuts import get_object_or_404

def index(request):
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status__exact=BookInstance.LOAN_STATUS.AVAILABLE).count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    queryset = Book.objects.filter(title__icontains='')[:5]
    template_name = 'catalog/book_list.html'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        return context
    
class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)
        return render(request, 'catalog/book_detail.html', context={'book': book})
    
class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'
    queryset = Author.objects.all()
    template_name = 'catalog/author_list.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        return context

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['books'] = Book.objects.filter(author=self.object)
        return context

django_projects/locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>{% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">{% block sidebar %}<ul class="sidebar-nav">
        {% load i18n %}
          <li><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
          <li><a href="{% url 'books' %}">{% trans 'All books' %}</a></li>
          <li><a href="{% url 'authors' %}">{% trans 'All authors' %}</a></li>
        </ul>{% endblock %}</div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}
        {% block pagination %}
          {% if is_paginated %} 
            <div class="pagination">
              <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page.obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %} 
              </span>
            </div>
          {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

django_projects/locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Author</h1>
  <p>Are you sure you want to delete the author '{{ author }}'?</p>

  <form method="post" action="{% url 'author-delete' author.id %}">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %} 
{% block content %}
{% load i18n %}
  <h1>{% trans 'Author' %}</h1>
  <p><strong>{% trans 'First name' %}:</strong>{{ author.first_name }}</a></p>
  <p><strong>{% trans 'Last name' %}:</strong> {{ author.last_name }}</p>
  <p><strong>{% trans 'Date of birth' %}:</strong> {{ author.date_of_birth }}</p>
  <p><strong>{% trans 'Date of death' %}:</strong> {{ author.date_of_death }}</p>
  <div class="detail">
    <h2>{% trans 'Books by' %}  {{ author }}</h2>
    <ul>
        {% for book in books %}
            <li> <a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% empty %}
            <li>{% trans 'No books available for this author.' %}</li>
        {% endfor %}
    </ul>
  </div>

{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
{% load i18n %}
  <h1>{% trans 'Author List' %} </h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">{{ author }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>{% trans 'There are author in the library' %}.</p>
  {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %} 
{% block content %}
{% load i18n %}
  <h1>{% trans 'Title' %}: {{ book.title }}</h1>
  <p><strong>{% trans 'Author' %}:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>{% trans 'Summary' %}:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>{% trans 'Language' %}:</strong> {{ book.language }}</p>
  <p><strong>{% trans 'Genre' %}:</strong> {{ book.genre.all|join:", " }}</p>
  <div class="detail">
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr />
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm'%}text-danger{% else %}text-warning{% endif %}">
      {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  {% load i18n %}
  <h1>{% trans 'Book List' %}</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
    <li>
      <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>{% trans 'There are no books in the library' %}.</p>
  {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew Book: {{ book_instance.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <p><input type="submit" value="Submit" /></p>
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Borrowed books</h1>
  
  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }}
        {% if perms.catalog.can_mark_returned %}
          <form method="post" action="{% url 'renew-book-librarian' bookinst.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link">Renew</button>
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No books currently borrowed.</p>
  {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Borrowed books</h1>
  
  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
        {% if perms.catalog.can_mark_returned %}
          <form action="{% url 'return-book' bookinst.id %}" method="post">
            {% csrf_token %}
<<<<<<< HEAD
            <input type="submit" value="Return" class="btn btn-primary">
=======
            <button type="submit" class="btn btn-primary">Return</button>
>>>>>>> 9538459 (Django Tutorial Part 8: User authentication and permissions)
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No books currently borrowed.</p>
  {% endif %}
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> 9538459 (Django Tutorial Part 8: User authentication and permissions)

django_projects/locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>
  {% load i18n %}
    <p>{% blocktrans count num_visits=num_visits %}You have visited this page {{ num_visits }} time{% plural %}You have visited this page {{ num_visits }} times{% endblocktrans %}</p>
{% endblock %}